frontier.myAccount.web/ViewComponents/DashboardHeaderViewComponent.cs
using frontier.myAccount.web.Services.Interfaces;


using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using frontier.myAccount.web.Models;
using Microsoft.AspNetCore.Mvc;

namespace frontier.myAccount.web.ViewComponents
{
    public class DashboardHeaderViewComponent : ViewComponent
    {
        private readonly IUserService _userService;
        public DashboardHeaderViewComponent(IUserService userService)
        {
            this._userService = userService;
        }

        public IViewComponentResult Invoke()
        {
            return View(_userService.GetLoggedInUser());
        }
    }
}

frontier.myAccount.web/Views/Shared/_Dashboard_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - frontier.myAccount.web</title>

    <environment include="Development">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/dist/css/dashboard.css" />
</head>

<body>

    @await Component.InvokeAsync("DashboardHeader")

    <div>
        @RenderBody()
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

frontier.myAccount.web/Views/Shared/_Footer.cshtml
<footer id="footer" class="fixedToBottom">
    <div class="footer-dark">
        <div class="container">
            <div class="row text-sm-center">
                <div class="col-xs-12 col-sm-6">
                    <a href="http://www.gexaenergy.com/terms-of-use/" target="_blank">Terms of Use</a>
                    <a href="http://www.gexaenergy.com/privacy-policy/" target="_blank">Privacy Policy</a>
                    <a href="http://www.gexaenergy.com/legal-notices-and-terms/" target="_blank">Legal Notices &amp; Terms</a>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <a href="http://www.gexaenergy.com/for-home/support/contact-us/" target="_blank">Contact Us</a>
                    <a href="mailto:customercare@gexaenergy.com">customercare@gexaenergy.com</a><br class="visible-xs" />
                </div>
            </div>
        </div>
    </div>
    <div class="footer-dark">
        <div class="container">
            <div class="row text-sm-center">
                <div class="col-xs-12 col-sm-6">
                    <p>&copy; Gexa Energy, LP All rights reserved</p>
                </div>
                <div class="col-xs-12 col-sm-6 text-right">
                    <p>PUCT CERTIFICATE #10027</p>
                </div>
            </div>
        </div>
    </div>
</footer>

frontier.myAccount.web/Views/Shared/_Header_Landing.cshtml
<nav class="navbar navbar-dark">
    <div class="container container-relaxed">
        <ul class="nav navbar-nav navbar-left">
            <li><small><span class="fa fa-rocket fa-rotate-45 fa-fw"></span> My Gexa </small></li>
        </ul>
        <ul class="nav navbar-nav navbar-right hidden-xs">
            <li><a href="#"><small><span class="fa fa-sign-out fa-white"></span> <span class="hidden-xs">Log in Or Sign Up for Great GEXA Energy Rates</span></small></a></li>
        </ul>
    </div>
</nav>
<nav class="navbar custom-nav">
    <div class="container container-relaxed">
        <div class="navbar-header">
            <div class="navbar-logo"> <img src="~/images/global/gexa-lq.png" alt="Gexa Energy" /> </div>
        </div>
    </div>
</nav>
<div class="homepage-hero-wrapper">
    <div class="homepage-hero-module">
        <div class=" visible-xs visible-sm"> <img src="~/images/home/Snapshots/aerial_houston_xs.jpg" alt=""> </div>
        <div class="video-container hidden-xs hidden-sm">
            <div class="filter"></div>
            <video autoplay loop class="fillWidth" id="login-video-player">
                <source src="~/images/home/WEBM/aerial_houston_xs.webm" type="video/webm" />
                Your browser does not support the video tag. I suggest you upgrade your browser.
                <source src="~/images/home/MP4/aerial_houston_xs.mp4" type="video/mp4" />
                Your browser does not support the video tag. I suggest you upgrade your browser.
            </video>
        </div>
    </div>
</div>

frontier.myAccount.web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - frontier.myAccount.web</title>

    <environment include="Development">
        @*<link rel="stylesheet" href="~/css/bootstrap.custom.css" />*@
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    <link rel="stylesheet" href="~/dist/css/landing.css" />

</head>

<body>

    <header>
        @await Html.PartialAsync("_Header_Landing");
    </header>

    @*@await Html.PartialAsync("../Account/Login.cshtml");*@

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_Footer");

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>